### PR TITLE
Update MongoDbPatternLayoutAppender.java to save timestamp as a date type in mongodb

### PR DESCRIPTION
**Pull request by pramodransingh**
adding code to save pattern layout timestamp in the mongodb as a Date type. Before it was getting saved as a string.

### CODE REVIEW

**Comment by RobertStewart** [comment]
Thanks for the contribution, but I'd like to request a few changes before I merge it.

1) I don't want to change the existing behavior of MongoDbPatternLayoutAppender, because this change will break compatibility for people already using it. Please create a new class named MongoDbPatternLayoutDateAppender that extends MongoDbPatternLayoutAppender and overrides append(). Since that means you would inherit only requiresLayout(), I'm fine if you either create an independent class or if you extract a protected method around where the bson variable is set and you override that.

2) You are missing imports for org.apache.log4j.Layout and java.util.Date, which prevents the code from compiling.

3) Please use the syntax conventions used in the rest of the code, e.g., a blank space before a ( and =.

Thanks!

**Comment by pramodransingh** [comment]
Thanks for sharing your feedback.

So here I am creating new independent class
MongoDbPatternLayoutDateAppender which extends the MongoDbAppender .
And overriding required methods.

Please have a look and let me know if any other changes needed.

Thanks,
Pramod

**Comment by RobertStewart** [comment]
Were you planning to update the pull request? I don't see any changes, yet.

**Comment by pramodransingh** [comment]
I am closing this PR and creating new one

**Comment by pramodransingh** [comment]
Following are the two PR:
https://github.com/RobertStewart/log4mongo-java/pull/12
https://github.com/log4mongo/log4mongo-java/pull/40

**Pull request closed without merging**
